### ISSUE TITLE
What kind of program is this?

### ISSUE THREAD

**Issue by lheydon** [Bill-Stewart/osinfo#1]
Hi,

Is this a Windows executable, or some kind of script?

Thanks.

LH

**Comment by Bill-Stewart** [comment]
It's a Windows executable. What's provoking the question? Have you looked at the [Releases](https://github.com/Bill-Stewart/osinfo/releases/tag/v1.0.0) section?

**Comment by lheydon** [comment]
> It's a Windows executable. What's provoking the question? Have you looked at the [Releases](https://github.com/Bill-Stewart/osinfo/releases/tag/v1.0.0) section?

Oh yes totally my bad, I had downloaded the ZIP file from the **Code** section rather than the **Releases** section. Sometimes Github can be confusing as all hell for us non-programmers!

**Comment by Bill-Stewart** [comment]
No problem!
